### ISSUE TITLE
nn.Transformer in self.bottle_neck 

### ISSUE THREAD

**Issue by ShinkyJ** [ZhaoRunning/Radio2Speech#3]
Hi !
Your work is truly impressive and has clearly involved a lot of dedication and expertise. 
I found your code in another project: https://github.com/kongto-yu/PJ_COMP9501/tree/main; but I am very confused of the link layer in generate model; it seems not work because of lacking parameter, which is in line 94 in https://github.com/kongto-yu/PJ_COMP9501/blob/main/model/generator.py. Can you explain this?
Thank you!

**Comment by ZhaoRunning** [comment]
I have released the code and weights, and you can check them.
